name: Hello World Reusable Workflow

on:
  workflow_call:
    inputs:
      name:
        description: "Name to greet"
        required: false
        type: string
        default: "World"

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, ${{ inputs.name }}!"
