name: Reusable Workflow

on:
  workflow_call:
    inputs:
      example_input:
        required: true
        type: string

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print input
        run: echo "Input: ${{ inputs.example_input }}"
